- sitedata/config.yml
- templates/base.html
- templates/index.html
Added a bootstrappy-looking button to the main page which links to registration website.
Also added event dates back to main page while I was there.
Should close issue #7
> add a registration button

- templates/schedule.html
- templates/workshop.html
> add workshop spotlights tab

- sitedata/daytoview.yml
Closing issue #34 (subject to some outstanding links)
> add zoom links to schedule

- sitedata/daytoview.yml
- sitedata/generate_preview_yaml.py
- sitedata/preview.yml
- templates/components.html
Closes #35, if this rework isn't desired we can revert to the previous version.
> Reshape pre-recorded content page and add all slideslive links

- templates/schedule.html
> Improved guidance page

- sitedata/preview.yml
- templates/components.html
> Various updates to pre-recorded content

- sitedata/daytoview.yml
> update speaker for TASTE

- sitedata/daytoview.yml
- templates/components.html
> Zoom numbers

- sitedata/daytoview.yml
> welcome back after lunch will be in same session as paper talks

- templates/base.html
Organization holds pages that are now less relevant including:
- Committee
- Sponsorship
- Call for papers
> Adds Organization to nav bar

- templates/base.html
- templates/content/register.md
This PR adds a link to the registration page in the navigation bar. It also updates the registration page to point the form for pre-registration. It also updates the text on the registration page to indicate the price and timeline for registration.
> Add updated registration information

- templates/content/call-for-papers-author-info.md
Adds updates to the CFP so that we can deploy and distribute the CFP broadly.
> Updates CFP per discussion

- templates/content/call-for-papers-author-info.md
> Spelling correction to CFP.

- templates/content/call-for-papers-author-info.md
Adopts language recommended by Proceedings for archival vs non-archival submissions.
> Updates language re archival submissions

- templates/content/call-for-papers-author-info.md
> Further updates language for archival submissions

- templates/content/call-for-papers-author-info.md
- templates/content/index.md
> tweak colour of buttons and add CFP deadline to main page

- templates/content/call-for-papers-author-info.md
Changes "encouraged" to "required" for LaTeX template as originally intended.
> Required use of LaTeX template

- templates/content/index.md
Add dates like author notification, etc. to the main page.
Also removed old text about the CFP deadline extension and the button to submit, since these are no longer necessary.
> add timeline

- templates/content/register.md
- templates/index.html
This PR:
- Updates the buttons on the home page and registration page from "Pre-register today" to "Register today"
- Updates the pricing on the registration page with early-bird and regular pricing
closes #126
> Update registration information

- scripts/requirements.txt
- sitedata/config.yml
- templates/base.html
- templates/live.html
This will enable RocketChat on the live page but doesn't add Chat to the navigation bar. This will be used for testing RocketChat.
> Enable RocketChat on the live page

- sitedata/schedule.yml
- templates/base.html
- templates/schedule.html
The schedule for 2022 has been added to the `schedule.yml` file and Schedule in the task bar has been enabled. Closes #140 .
> Add calendar / schedule for CHIL 2022

- sitedata/schedule.yml
This adds an updated/final schedule to the website.
> Add final schedule to website

- templates/components.html
This adds a link to open chat in a new browser tab and expands the size of the embedded chat
> Update Rocketchat embedded iframe size and add link to open chat in a new tab

- sitedata/schedule.yml
Gathertown -> Gather
"Watch live" -> Livestream
> update terminology in schedule to be more consistent

- main.py
- templates/components.html
- templates/content/media-release.md
- templates/live.html
This adds a media release statement to the live.html page. Closes #161 .
> Add media release section

- templates/base.html
- templates/components.html
- templates/live.html
- Capitalizing "Useful links" section to align with the format of the rest of the titles (e.g., "CHIL Sponsors")
- Changing footer to 2022 vs 2021
> Minor changes

- sitedata/sponsors.csv
- templates/base.html
- templates/content/sponsor.md
1. Updates sponsorship information
2. Removes previous year's sponsor footer
> Update sponsorship information

- templates/base.html
- templates/content/call-for-papers-author-info.md
- templates/content/call-for-papers-track-1.md
- templates/content/call-for-papers-track-2.md
- templates/content/call-for-papers-track-3.md
- templates/content/committee-governing-board.md
- templates/content/sponsor.md
Main update is Call for Papers (CFP); a couple of edits to the CHIL committee, as well as to the sponsors' page.
> Updating CFP 

- templates/content/call-for-papers-author-info.md
Updating conference dates in the CFP.
> update conf dates

- templates/content/call-for-papers-author-info.md
- templates/content/index.md
Pushing LaTex template + required sections as well as 2023 OpenReview site links.
> Adding LaTex template + OpenReview submission site

- main.py
- templates/base.html
- templates/content/index.md
- templates/content/schedule.md
- templates/tentative-schedule.html
Changing submit CFP -> lightning talk.
> Updating submit button to lightning talk

- templates/base.html
This PR updates the text in the footer on the website to 2024 CHIL Organization Committee instead of 2023 CHIL Organization Committee.
> Update footer text

- requirements-dev.txt
- requirements.txt
This PR pins the package versions in `requirements.txt` for compatibility. It also removes the `requirements-dev.txt` file. If there are needed packages which aren't in `requirements.txt`, I will update it accordingly as working on the site for this years conference.
> Update package requirements

- sitedata/sponsors.csv
This adds a link for 2024 sponsor; The Chase Center at UPenn.
> Add sponsor link

- sitedata/sponsors.csv
- templates/base.html
This adds the logo and link for the University of Minnesota
> Add 2024 sponsor University of Minnesota

- templates/content/call-for-papers-author-info.md
Add note about senior area chairs submission restrictions.
> Update author info

- templates/content/call-for-papers-reviewer.md
This pull request adds reviewer guidelines for CHIL 2024. The guidelines are based on guidelines from CHIL 2023, with a few updates and improvements. Briefly, I:
1. Removed dates to make the page easier to maintain. Dates are accessible on other pages.
2. Made minor changes to language for style and readability.
3. Added a comment to say that reviews are subject to quality/content checks.
The content is copied below for convenience:
---
Reviewing is a critical service in any research community, and we highly respect the expertise and contributions of our reviewers. Every submission deserves thoughtful, constructive feedback that:
1. Selects quality work to be highlighted at CHIL; and
2. Helps authors improve their work, either for CHIL or a future venue.
To deliver high-quality reviews, …
> Add guidelines for reviewers for CHIL 2024

- templates/content/call-for-papers-author-info.md
Minor change to fix the title of Track 3.
"Policy: Impact and Society: Policy, Public Health, Social Outcomes, and Economics" -> Impact and Society: Policy, Public Health, Social Outcomes, and Economics
> Fix title for Track 3

- templates/content/call-for-papers-author-info.md
Following discussion today with @mmcdermott and others, we have been asked to change EST to Anywhere on Earth (AoE). We will make the corresponding change in OpenReview shortly.
> Switch from EST to AoE

- templates/index.html
Updates the conferenceStartDate variable.
> Update conferenceStartDate variable

- templates/content/call-for-papers-author-info.md
This PR updates the dates on the Call for Papers page.
> Update dates on call for papers page

- templates/content/call-for-papers-author-info.md
> Add call for papers date

- templates/base.html
- templates/call-for-papers.html
- templates/content/call-for-doctoral.md
- templates/index.html
This updates information regarding the call for papers and adds a page of information about submitting for the doctoral symposium.
> Update call for papers and doctoral symposium

- templates/index.html
This PR changes the Pre-register button to Register Now for the opening of registration for the conference.
> Open 2024 registration

- static/css/global.css
- templates/base.html
- templates/components.html
- templates/content/index.md
- templates/content/schedule-fri.md
- templates/content/schedule-thurs.md
- templates/speakers.html
This PR adds links from the home page and program page to the relevant speaker(s) on the speaker bio page.
> Add links to speaker profiles

- static/css/global.css
- templates/content/call-for-doctoral.md
- templates/index.html
This removes the button and link to apply for the doctoral symposium.
> Remove doctoral symposium application button and link

- templates/index.html
This adds a "Call for Volunteers" button to the home page.
> Add volunteers button

- sitedata/sponsors.csv
This PR fixes the IDs in the sponsors.csv
> Fix sponsors csv

- sitedata/sponsors.csv
This PR fixes a syntax error in the sponsor.csv
> Fix sponsor csv syntax

- static/css/global.css
- templates/content/travel.md
This adjust the image sizes on the travel page.
> Adjust image sizing on travel page

- main.py
- templates/base.html
This PR adds a page to acknowledge reviewers.
> Add reviewer acknowledgements page

- sitedata/config.yml
Adds June 27 - 28 on home page
> Adds days on home page

- templates/base.html
- templates/proceedings.html
This makes some syntax updates and deletes some old comments
> Clean accepted papers files

- templates/acknowledgements.html
- templates/content/acknowledgements.md
These pages didn't get added in #243 as needed
> Adding missing acknowledgements pages

- templates/content/schedule-thurs.md
Update Kate Link's tutorial title.
> Update tutorial title

- templates/content/schedule-fri.md
- templates/content/schedule-thurs.md
This adds information about the moderators to the schedule for the Panels.
> Add moderators for 2024 Panels
