ahli-org/chil-website

- main.py
- sitedata/daytoview.yml
- templates/components.html
- templates/schedule.html
This pull request adds functionality for single day schedules, as requested in #17. The programme details will need to be added to the sitedata/daytoview.yml file (https://github.com/acm-chil/acm-chil-website/compare/master...acm-chil:days?expand=1#diff-a746c61c28f7040566241c5128c4a8b6)
> Adds template for single day schedules

- sitedata/daytoview.yml
- templates/components.html
This change updates the day to view template to respond to the following request in #17 :
> 0) Remove the "Read More" Column.
> 
> Change the "Video link" Column to be "Session Link".
> Include two link fields for A) the session docpage and B) the session Zoom link.
> Make the "Title" Column text link to the specified session docpage link.
> Make the "Session Link" Column text link to the specified Zoom link.
> Update the "day to view" template to include HTML links. Ref #17

- templates/schedule.html
Removes the calendar page, and instead defaults to the schedule for Thursday. Follows discussion in #22.
The calendar doesn't add anything at the moment, and adds to overhead in keeping the site updated.
> remove calendar. ref #22

- sitedata/daytoview.yml
Should fix #49, switching from webinar to meeting links
> update zoom links for keynotes/intros

- sitedata/daytoview.yml
Adds two tutorial authors (Amy Pitelka and Katie Li) to the "daytoview", Follows the comment at: https://github.com/acm-chil/acm-chil-website/pull/57#issuecomment-662031951
> Add tutorial authors to "daytoview"

- templates/call-for-papers.html
- templates/content/call-for-papers.md
- templates/content/schedule.md
- templates/schedule.html
Proposal for (temporary) content for Schedule and CFP pages, featuring 2020 content, while we work out proper archiving strategy.
> manually populate CFP and schedule with summarised data from 2020

- templates/content/call-for-papers-track-3.md
Just reorganizes the content to flow better
I don't think "at least one sub-discipline upon abstract registration" is clear to individuals, maybe we should list out the sub-disciplines?
> Reorganize CFP text for track 3

- templates/content/register.md
Fixes #107. Renames "ACM Member" -> "Student" and "Non-ACM Member" -> "Non-Student" to remove reference to ACM.
Please take a look and deploy after merging.
> Removes reference to ACM

- templates/content/index.md
- templates/index.html
This adds a button for paper submissions to the homepage. The submit your paper button on the call for papers page remains as well.
> Adds a button for paper submissions to the homepage

- sitedata/sponsors.csv
- templates/base.html
- templates/index.html
This PR adds the 2022 sponsor logos to the footer of each page on the website.
closes #127
> Add sponsor logos to website pages

- templates/index.html
As discussed in https://github.com/ahli-org/chil-website/pull/124, currently the [schedule countdown](http://chilconference.org/) displays weeks, days, hours and minutes. @corcra if we want to remove hours and minutes, then I think this pull request should do it. Please check though! Something more sophisticated might be needed.
> Remove hours and minutes from the countdown

- templates/content/index.md
We need to put the date of the _next_ day, so that it won't be crossed out until the _end_ of the day.
> fix off-by-one error on the countdown

- sitedata/config.yml
- templates/base.html
Adding auth0 information in the config.yml file; useful for us testing that out (+rocketchat) prior to enabling the "live" and "chat" tabs as part of the deployed website.
> Auth0 setup

- sitedata/schedule.yml
This corrects the breakout session times for:
- Responsible AI for health
- Social and environmental determinants of health
The Schedule_CHIL 2022 Google Doc has also been updated so that these incorrect times won't get added back in on a future schedule update. Closes #142 .
> This corrects the breakout session times on day 1

- templates/live.html
This updates the top of the live page to show the embedded SlidesLive stream for Day 1 - April 7th. It also adds the `slideslive_id` for Day 2 to the code. After Day 1 ends, we can replace the active embedded section for Day 1 with the section for Day 2.
> This updates the SlidesLive section on the live page

- templates/components.html
This adds a note above the RocketChat iframe which instructs users to use the "Login via Auth0" button to log into RocketChat.
> Add instructions for logging into RocketChat to the live page

- templates/live.html
This removes the Day 1 + date from the live page so that it won't need to be updated after Day 1 for the start of Day 2.
> Remove date from live page

- templates/base.html
- templates/components.html
This adds jQuery code to prevent focus from jumping to the embedded rocket.chat iframe. Closes #73 .
> Prevent focus from shifting to embedded rocket.chat on the `live.html` page

- templates/content/live.md
Adds the link to our current gather.town space to the bottom of the live page, and removes the "see schedule for details" bit (as I am not sure what details we are alluding to there).
Password will be communicated directly to registered attendees.
> add link to gather town to live page

- static/css/pages/live.css
- templates/content/live.md
- templates/live.html
Adds the links to zoom tutorials for day 1 and day 2 to the live page. Does not include the passwords for said meetings.
I was fighting with the flexbox that the snowman and gather text were contained in, so I just removed it for simplicity. This section fo text now matches the rocket.chat instructions in aesthetics.
> Add zoom links to live page

- templates/base.html
The `if` statement needed to be moved inside the `script` tag and it uses `.length` instead of `.val` since `.val` was not working to detect the iframe `id`. The original PR was #156 .
> This fixes the rocket.chat focus script

- templates/base.html
- templates/content/call-for-papers-author-info.md
- templates/index.html
This PR should not be deployed to the website until registration closes. 
The PR adds Livestream links which point to `live.html`. It also removes the navigation bar tab for Registration. Lastly, it shifts the navigation bar tab for Call For Papers to the right, so the more relevant tabs are all to the left of the navigation bar. Closes #150 .
> Add links to the live page and remove navigation to Registration

- templates/schedule.html
This makes the Friday tab on the schedule page the default tab, as desired for day 2.
> For schedule page, make Friday tab the default/active tab for day 2

- templates/schedule.html
PR #167 changes the default tab but not the actual default schedule content; this PR fixes that issue.
> Switching default schedule content to be Friday's

- templates/components.html
- templates/live.html
- templates/schedule.html
- Introducing a block "livestream_subsection" to enable centering the title indicating the day of each stream
- Setting Thursday (day 1) as the default day of the schedule page
> Post-conference changes

- templates/content/call-for-doctoral.md
- templates/content/call-for-papers-author-info.md
- templates/content/call-for-papers-reviewer.md
- templates/content/index.md
Modifying dates on landing page, doctoral symposium, and author+reviewer pages for the next timeline.
> Updating for CFP extension to 2/15

- templates/content/call-for-papers-author-info.md
This PR adds a link to the Overleaf template for the 2024 conference.
> Add Overleaf template link

- sitedata/sponsors.csv
- templates/base.html
This adds sponsor information to the website for the Chase Center at UPenn and Health Data Science.
> Add two new 2024 sponsors

- templates/call-for-papers.html
- templates/content/call-for-papers-author-info.md
- templates/index.html
This PR adds a button to the homepage and at the top of the "call for papers" page for paper submissions. It also adds a link to the text further below on the "call for papers" page.
> Add buttons and links for paper submissions

- archive/sitedata/2021/highlights.md
- archive/sitedata/2022/highlights.md
- templates/content/call-for-papers.md
- templates/live.html
- templates/program.html
This removes some old April dates on the website. A post to LinkedIn scraped the websites and indicates that the June 2024 conference is on April 7th - 8th, 2022.
> Remove April dates
